name: Start Site
on:
  push:
    branches:
      - main
    tags:
      - "!*"
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: xcratch/xcx-example
          ref: main
          path: ./xcx-example
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./xcx-example
          keep_files: true
